version: '3'

services:
  keycloak:
    container_name: keycloak
    image: docker.io/bitnami/keycloak:21.1.2
    depends_on:
      - postgresql-kc
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_HOST=postgresql-kc
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=bitnami_keycloak
      - KEYCLOAK_DATABASE_USER=bn_keycloak
    ports:
      - "80:8080"

  postgresql-kc:
    container_name: postgresql-kc
    image: docker.io/bitnami/postgresql:15
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  sonarqube:
    container_name: sonarqube
    image: docker.io/bitnami/sonarqube:10
    ports:
      - '9000:9000'
    volumes:
      - 'sonarqube_data:/bitnami/sonarqube'
      - ./sonarqube:/docker-entrypoint-init.d
    depends_on:
      - postgresql-sq
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - SONARQUBE_DATABASE_HOST=postgresql-sq
      - SONARQUBE_DATABASE_PORT_NUMBER=5432
      - SONARQUBE_DATABASE_USER=bn_sonarqube
      - SONARQUBE_DATABASE_NAME=bitnami_sonarqube
      - SONARQUBE_USERNAME=admin
      - SONARQUBE_PASSWORD=password

  postgresql-sq:
    container_name: postgresql-sq
    image: docker.io/bitnami/postgresql:15
    volumes:
      - 'postgresql_sq_data:/bitnami/postgresql'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_sonarqube
      - POSTGRESQL_DATABASE=bitnami_sonarqube

volumes:
  postgresql_data:
    driver: local

  postgresql_sq_data:
    driver: local

  sonarqube_data:
    driver: local
